/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceivablesIndexRouteImport } from './routes/receivables/index'
import { Route as PayablesIndexRouteImport } from './routes/payables/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceivablesIndexRoute = ReceivablesIndexRouteImport.update({
  id: '/receivables/',
  path: '/receivables/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayablesIndexRoute = PayablesIndexRouteImport.update({
  id: '/payables/',
  path: '/payables/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/payables/': typeof PayablesIndexRoute
  '/receivables/': typeof ReceivablesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/payables': typeof PayablesIndexRoute
  '/receivables': typeof ReceivablesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/payables/': typeof PayablesIndexRoute
  '/receivables/': typeof ReceivablesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard/' | '/payables/' | '/receivables/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/payables' | '/receivables'
  id: '__root__' | '/' | '/dashboard/' | '/payables/' | '/receivables/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  PayablesIndexRoute: typeof PayablesIndexRoute
  ReceivablesIndexRoute: typeof ReceivablesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receivables/': {
      id: '/receivables/'
      path: '/receivables'
      fullPath: '/receivables/'
      preLoaderRoute: typeof ReceivablesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payables/': {
      id: '/payables/'
      path: '/payables'
      fullPath: '/payables/'
      preLoaderRoute: typeof PayablesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  PayablesIndexRoute: PayablesIndexRoute,
  ReceivablesIndexRoute: ReceivablesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
